name: Tweaky
main: me.colingrimes.tweaky.Tweaky
version: ${version}
api-version: 1.21
author: Scill
commands:
  tweaky:
    description: Main command for the Tweaky plugin.
  tweaks:
    description: Opens up the Tweaks menu.
    aliases: [tweak]
  coordinates:
    description: Toggles the coordinates HUD.
    aliases: [coords]