name: Tweaky
main: me.colingrimes.tweaky.Tweaky
version: ${version}
api-version: 1.21
author: Scill
commands:
  tweaky:
    description: Main command for the Tweaky plugin.
    aliases: [tweaks, tweak]